### ISSUE TITLE
Hide your password

### ISSUE THREAD

**Issue by giladyavneh** [suvelocity/challengeme#107]
When you press the eye icon upon entering a password in the registration page, and then drag the mouse while it is still clicked, and then release, the password stays viseable. It is probably becuase the 'mouseup' event is appended to the eye icon, hence when you release the mouse while not on thw icon, the event won't fire.
Two possable solutions:
1. Have the 'mouseup' event be appended on thw window object.
2. Add an 'mouseout' event that also hides the password

**Comment by david35008** [comment]
fixed
