### ISSUE TITLE
On deploy to production/staging there is a downtime

### ISSUE THREAD

**Issue by Cyber4sPopo** [suvelocity/challengeme#29]
When you push to master/staging the ci/cd process cause a downtime:

<img width="794" alt="Screen Shot 2020-10-10 at 14 41 40" src="https://user-images.githubusercontent.com/69596366/95654177-e7b46280-0b06-11eb-9ebe-50f49813db09.png">

**Comment by ItsDrTsach** [comment]
@Cyber4sPopo  what do you mean by that? not sure...
