### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by tomeryp** [suvelocity/challengeme#5]
- Entering the webapp from main path (http(s)://{BASEURL}/) should redirect to the login page (unless already logged in, see last list item)
- Login page should be in path http(s)://{BASEURL}/login
- Navigating to any other path (http(s)://{BASEURL}/whatever) while not logged in, should also lead to the login page
- Logging in with wrong user pass combo should show an error to the user
- Entering a correct username+password should navigate the user to the main screen located in the http(s)://{BASEURL}/ path route
- A user not active in over 24 hours should be logged out automatically

- Login page should have a link to a registration page
- Registration page should let the user register a new user with a user+pass combo
- Once logged in, the user should be able to logout from any screen

- The user will be auto logged off if not refreshed in over 24hrs

**Comment by david35008** [comment]
done
