### ISSUE TITLE
Main screen - challenge list and & add new challenge

### ISSUE THREAD

**Issue by tomeryp** [suvelocity/challengeme#7]
Each challenge in main screen list should have the following info data:
- Challenge name
- Creation date
- Shortened description
- Creator name
- Cover image
- Github repo link
- Average rating

Main screen should have a button to add a new challenge.
Pressing this button should redirect to a dedicated form page for adding a new challenge to the system.

The New-Challenge form should have the following data for submission:
- Challenge name
- Github repository link
- Description textbox
- Cover image upload
- Challenge type dropdown
- Submit button to send this data to the server

The server will validate the data (valid repo link, valid image dimensions etc)
If the server responds with an error for the data submitted, the data should be displayed to the user in a user-friendly way

The server should expose api for get all the available challenge types that exist in the system - according to the content of  folder: `.github/workflows`

**Comment by david35008** [comment]
done
