### ISSUE TITLE
After filtering label the label disapear

### ISSUE THREAD

**Issue by Cyber4sPopo** [suvelocity/challengeme#81]
steps:

- Choose some label in the label multi select
- Click filter
![Screen Shot 2020-10-19 at 20 26 16](https://user-images.githubusercontent.com/69596366/96490486-8e0c1080-1249-11eb-897d-0e6771ecbd03.png)

current result:
The filter get empty
![Screen Shot 2020-10-19 at 20 26 23](https://user-images.githubusercontent.com/69596366/96490478-8a788980-1249-11eb-9cc2-6a0c88792ca4.png)

expected result:
I want to see while filtering labels which label the app filter by and be able to modify it

**Comment by ywais** [comment]
Same result when clicking on a label in the single challenge page.
You get the home page filtered by that label but with no indication in the select box or in the address bar.

**Comment by RoyShnitzel** [comment]
done
