### ISSUE TITLE
failed submission message

### ISSUE THREAD

**Issue by ywais** [suvelocity/challengeme#89]
When the submitted repo failed the tests, no message or explanation is displayed.

**FAIL:**
![image](https://user-images.githubusercontent.com/67857593/96494970-cdd5f680-124f-11eb-9263-279099ff37ea.png)

**SUCCESS:**
![image](https://user-images.githubusercontent.com/67857593/96495001-db8b7c00-124f-11eb-94b3-9db272bc3f65.png)

**Comment by david35008** [comment]
fixed
